version: '3'

volumes:
  .ipython_data_local: {}

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    platform: linux/amd64
    volumes:
      - .:/home/user/app
      - .ipython_data_local:/root/.ipython/profile_default
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=development-secret
      - DEBUG=True
      - DATABASE_URL=sqlite:////home/user/app/database.sqlite3
      - CSRF_TRUSTED_ORIGINS=http://localhost
